default: sema rdv1 rdv2 lecteur redacteur

sema: sema.c
	gcc sema.c -o sema

rdv1: RDV.c
	gcc RDV.c -o RDV

rdv2: RDV2.c
	gcc RDV2.c -o RDV2

lecteur: lecteur.c
	gcc lecteur.c -o lecteur

redacteur: redacteur.c
	gcc redacteur.c -o redacteur